#!/bin/bash

WAK=`grep PASS_WARN_AGE /etc/login.defs | grep -v "#" | awk -F " " '{print $2}'`

echo -ne "Control: 5.5.1.3 Ensure password expiration warning is 7 days or more: "

if [[WAK -gt 6]]
then
  echo "PASS"
else
  echo "FAIL"
fi
